import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Header from "../components/Header";
// import Navbar2 from "../components/Navbar2";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  });

export const metadata: Metadata = {
  title: "Prowash of the GrandStrand | Serving Myrtle Beach",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children:React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <section className='py-10'>
          <div className='container'>
          <div>
            <Header/>
            {children}
            <Footer />
          </div>
          </div>
        </section>
      </body>
    </html>
  );
}
